import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

const figree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={figree.className + "bg-light antialiased min-h-[100dvh]"}
      >
        {children}
      </body>
    </html>
  );
}
